services:
  api-gateway:
    image: yogeshoza33333/test-api-gateway:latest
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    container_name: test-api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=hjbascbkhesf324hcsjknsdc
      - USER_SERVICE_URL=http://user-service:3001
      - WORKSHEET_SERVICE_URL=http://worksheet-service:3002
      - PAYMENT_SERVICE_URL=http://payment-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3004
      - API_GATEWAY_URL=http://localhost:3000
    depends_on:
      - user-service
      - worksheet-service
      - payment-service
      - notification-service
    networks:
      - test-network

  user-service:
    image: yogeshoza33333/test-user-service:latest
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: test-user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URL=mongodb+srv://yogesh3332:tCGdpj1IHnID13J4@cluster0.pwjc7nq.mongodb.net/microservice?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=hjbascbkhesf324hcsjknsdc
    networks:
      - test-network

  worksheet-service:
    image: yogeshoza33333/test-worksheet-service:latest
    build:
      context: ./backend/worksheet-service
      dockerfile: Dockerfile
    container_name: test-worksheet-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URL=mongodb+srv://yogesh3332:tCGdpj1IHnID13J4@cluster0.pwjc7nq.mongodb.net/microservice?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=hjbascbkhesf324hcsjknsdc
    networks:
      - test-network

  payment-service:
    image: yogeshoza33333/test-payment-service:latest
    build:
      context: ./backend/payment-service
      dockerfile: Dockerfile
    container_name: test-payment-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGODB_URL=mongodb+srv://yogesh3332:tCGdpj1IHnID13J4@cluster0.pwjc7nq.mongodb.net/microservice?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - test-network

  notification-service:
    image: yogeshoza33333/test-notification-service:latest
    build:
      context: ./backend/notification-service
      dockerfile: Dockerfile
    container_name: test-notification-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
    networks:
      - test-network

  frontend:
    image: yogeshoza33333/fractal-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: test-frontend
    ports:
      - "4005:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - api-gateway
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
